# Generated by Django 3.0.5 on 2020-07-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='student',
            table=None,
        ),
    ]
